# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec36df0c7438b081282a32c5b01decc1a5f6a909c2006609cc130a11fb98df6137416b005dcbd5fa0d0355dcc871d260725fed39d016438195b9a025c7f539aa

test:
  secret_key_base: 66d77adcd2d3afd3ace8cd463f01908d82559f5231d2e90042a495b8020104c72979dd011549d9dd3afbf25988efaa5d43846eaafe5344a866b989974e88e4e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
